### ISSUE TITLE
Finite Field Artithmetic not implemented?

### ISSUE THREAD

**Issue by TBCode523** [ionspin/kotlin-multiplatform-libsodium#45]
I haven't been able to find functions relating to libsodiums [Finite Field arithmetic](https://doc.libsodium.org/advanced/point-arithmetic#scalar-multiplication). If they're available how do I invoke them? Thanks.

**Comment by ionspin** [comment]
Hi @TBCode523, you are right, finite field arithmetic is not implemented in the library. 

Pull request for that would be welcome! 

Adding it would be relatively straightforward, the java and native should be present since we are building the library from source, and I think I saw them in libsodium.js which we use for JS target, but I haven't checked if all of them are there.

**Comment by TBCode523** [comment]
I'm not experienced with developing cryptographic related algorithms, but I can take a look if more senior developers are unavailable.

**Comment by Traderjoe95** [comment]
I could take over, if you don't mind. I've got some experience with this and also brought support for Ristretto to [LazySodium](https://github.com/terl/lazysodium-java) some time ago.
