### ISSUE TITLE
Proper use of Libsodium return codes

### ISSUE THREAD

**Issue by ReneeVandervelde** [ionspin/kotlin-multiplatform-libsodium#49]
Libsodium seems to have a consistent strategy [documented](https://doc.libsodium.org/quickstart#how-do-i-check-if-a-function-call-succeeded) for its return codes. However, I am seeing multiple different strategies for handling the returns from api calls in the library: [[1]](https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/0.9.2/multiplatform-crypto-libsodium-bindings/src/commonMain/kotlin/com.ionspin.kotlin.crypto/GeneralLibsodiumException.kt) [[2]](https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/0.9.2/multiplatform-crypto-libsodium-bindings/src/jvmMain/kotlin/com/ionspin/kotlin/crypto/secretbox/SecretBox.kt#L32-L34) [[3]](https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/0.9.2/multiplatform-crypto-libsodium-bindings/src/jvmMain/kotlin/com/ionspin/kotlin/crypto/signature/SignatureJvm.kt#L42-L44).

Is there a rationale for this? or is there need for some clean up here?

My concern is primarily with the strategy of checking for an error code, such as in this method:
```kotlin
fun Int.ensureLibsodiumSuccess() {
  if (this == -1) {
    throw GeneralLibsodiumException()
  }
}
```
This seems like it should be **inverted** to check for a successful code rather than the error code, or it could inadvertently return successful if an unknown error code is returned.

**Comment by ionspin** [comment]
Hi @ReneeVandervelde, I agree, it would be better to check for success and throw if it's not successful. The separate exceptions in the cases you mentioned were my attempt at making the API more kotlin-like but I was not consistent with it (although I did find it useful when using the library). In any case those should also check for success like [[2]](https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/0.9.2/multiplatform-crypto-libsodium-bindings/src/jvmMain/kotlin/com/ionspin/kotlin/crypto/secretbox/SecretBox.kt#L32-L34)

Thanks for pointing it out.

**Comment by ReneeVandervelde** [comment]
Thanks for confirming! Wanted to check if there was some reason for it.

(fyi - I noticed this while digging through the code to do a personal [audit] of the code. I'm just one pair of eyes 👀, but hopefully you find that useful. I may try to take on some of the suggestions like this one when I get some time)

[audit]: https://reneevandervelde.com/publications/expect-fun/audit-ionspin-kmp-libsodium.html

**Comment by ionspin** [comment]
Your personal audit is highly appreciated, and I find it very useful! I agree with your findings and would love to convert it into issues that can be tackled one at a time. 

One of the larger points that I have been deliberating on for quite some time is removing 'resource-loader'library  and implementing the functionality directly in the library. Since it would be specific to this library, the implementation would be presumably much simpler.

Also one concern of mine related to building libsodium: while most of the libsodium targets are built from a libsodium submodule, JS target is included as a npm dependency https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/509d22ed0552188ced522c7304186b33fdbb8332/buildSrc/src/main/kotlin/Deps.kt#L69

I am not completely clear on the consequences of this as I rarely use JS target.

And java windows DLL is downloaded from libsodium website. I presume that it could be replaced with the mingw dll that is built from submodule.

At some point I'd like to be able to build all libsodium targets including JS in my CI/CD but It'll take some time, which is at the moment quite a limited resource.

Once again, I'm very appreciative of your audit, and hope that in the next release most if not all concerns from your audit are addressed!

**Comment by ionspin** [comment]
Also, I'd like to include link to your audit in the README next time I bump the version, if that is fine with you?
